version: '3.8'

services:
  dnd-bot:
    build: .
    container_name: dnd-bot
    restart: unless-stopped
    env_file: .env
    depends_on:
      - redis
    networks:
      - dnd-network

networks:
  dnd-network:
    driver: bridge

volumes:
  redis-data:
    driver: local 